# Generated by Django 3.2.6 on 2021-10-01 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_reviews_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='url',
        ),
    ]
