# Generated by Django 3.2.6 on 2021-10-07 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_auto_20211003_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.PositiveSmallIntegerField(default=2021, verbose_name='Дата выхода'),
        ),
    ]
